#!/bin/bash

POPPLER_VERSION=${POPPLER_VERSION-21.09.0}
POPPLER_TARBALL_URL="https://poppler.freedesktop.org/poppler-${POPPLER_VERSION}.tar.xz"
TEMP_DIR=$(mktemp -d /tmp/poppler.XXXXXXXXXX)

apt-get update && \
apt-get -y install libcairo2-dev libjpeg-dev libgif-dev && \
apt-get -y install cmake libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev

echo "Serving files from /tmp on $PORT"
cd /tmp
python -m http.server $PORT &

cd $TEMP_DIR
echo "Temp dir: $TEMP_DIR"

echo "Downloading $POPPLER_TARBALL_URL"
curl -L $POPPLER_TARBALL_URL | tar xJ

cd poppler-${POPPLER_VERSION}
mkdir build
cd build/
cmake  -DCMAKE_BUILD_TYPE=Release   \
       -DCMAKE_INSTALL_PREFIX=/usr  \
       -DTESTDATADIR=$PWD/testfiles \
       -DENABLE_UNSTABLE_API_ABI_HEADERS=ON \
       ..
make
make install

cp /usr/bin/pdftotext $1
